# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dk_api_client
from dk_api_client.api.product_search_api import ProductSearchApi  # noqa: E501
from dk_api_client.rest import ApiException


class TestProductSearchApi(unittest.TestCase):
    """ProductSearchApi unit test stubs"""

    def setUp(self):
        self.api = dk_api_client.api.product_search_api.ProductSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_associations(self):
        """Test case for associations

        Retrieve Associations for a given product  # noqa: E501
        """
        pass

    def test_categories(self):
        """Test case for categories

        Returns all Product Categories. Category Id can be used in KeywordRequestDto.Filters.TaxonomyIds to restrict a  keyword search to a given category  # noqa: E501
        """
        pass

    def test_categories_by_id(self):
        """Test case for categories_by_id

        Returns Category for given Id. Category Id can be used in KeywordRequestDto.Filters.TaxonomyIds to restrict a  keyword search to a given category  # noqa: E501
        """
        pass

    def test_digi_reel_pricing(self):
        """Test case for digi_reel_pricing

        Calculate the DigiReel pricing for the given DigiKeyProductNumber and RequestedQuantity  # noqa: E501
        """
        pass

    def test_keyword_search(self):
        """Test case for keyword_search

        KeywordSearch can search for any product in the Digi-Key catalog.  # noqa: E501
        """
        pass

    def test_manufacturers(self):
        """Test case for manufacturers

        Returns all Product Manufacturers. ManufacturersId can be used in KeywordRequestDto.Filters.ManufacturerIds to  restrict a keyword search to a given Manufacturer  # noqa: E501
        """
        pass

    def test_media(self):
        """Test case for media

        Retrieve all media for a given product  # noqa: E501
        """
        pass

    def test_package_type_by_quantity(self):
        """Test case for package_type_by_quantity

        Provide a product number and quantity to receive product information such as pricing, available quantity, and the  best  packaging type for the requested quantity of the product.  For example, given a requested quantity larger than a standard reel, this will return information about the  standard tape and reel as well as either cut tape or DKR depending on the provided preference.  Made for Cut Tape, Tape and Reel, and Digi-Reel products only. Other packaging types can be searched for, but  results may vary.  Locale information is required in the headers for accurate pricing and currencies. Locale defaults to United  States.  # noqa: E501
        """
        pass

    def test_product_details(self):
        """Test case for product_details

        Retrieve detailed product information including real time pricing and availability.  # noqa: E501
        """
        pass

    def test_recommended_products(self):
        """Test case for recommended_products

        Returns a list of recommended products for the given Product number.  # noqa: E501
        """
        pass

    def test_substitutions(self):
        """Test case for substitutions

        Retrieve Substitutions for a given product  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
