# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.manufacturers_response import ManufacturersResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestManufacturersResponse(unittest.TestCase):
    """ManufacturersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManufacturersResponse(self):
        """Test ManufacturersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.manufacturers_response.ManufacturersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
