# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.media_links import MediaLinks  # noqa: E501
from swagger_client.rest import ApiException


class TestMediaLinks(unittest.TestCase):
    """MediaLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaLinks(self):
        """Test MediaLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.media_links.MediaLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
