# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dk_api_client
from dk_api_client.models.filter_options_request import FilterOptionsRequest  # noqa: E501
from dk_api_client.rest import ApiException


class TestFilterOptionsRequest(unittest.TestCase):
    """FilterOptionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterOptionsRequest(self):
        """Test FilterOptionsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dk_api_client.models.filter_options_request.FilterOptionsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
