# coding: utf-8

"""
    ProductSearch Api

    ProductSearch Api  # noqa: E501

    OpenAPI spec version: v4
    Contact: dl_Agile_Team_B2B_API@digikey.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.base_filter_v3 import BaseFilterV3  # noqa: E501
from swagger_client.rest import ApiException


class TestBaseFilterV3(unittest.TestCase):
    """BaseFilterV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseFilterV3(self):
        """Test BaseFilterV3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.base_filter_v3.BaseFilterV3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
