{'category': {'id': 60, 'product_count': None, 'value': 'Ceramic Capacitors'},
 'filter_values': [{'product_count': 16,
                    'range_filter_type': None,
                    'value_id': '0.1 pF',
                    'value_name': '0.1 pF'},
                   {'product_count': 31,
                    'range_filter_type': None,
                    'value_id': '0.2 pF',
                    'value_name': '0.2 pF'},
                   {'product_count': 40,
                    'range_filter_type': None,
                    'value_id': '0.3 pF',
                    'value_name': '0.3 pF'},
                   {'product_count': 32,
                    'range_filter_type': None,
                    'value_id': '0.4 pF',
                    'value_name': '0.4 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '0.47 pF',
                    'value_name': '0.47 pF'},
                   {'product_count': 91,
                    'range_filter_type': None,
                    'value_id': '0.5 pF',
                    'value_name': '0.5 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '0.56 pF',
                    'value_name': '0.56 pF'},
                   {'product_count': 33,
                    'range_filter_type': None,
                    'value_id': '0.6 pF',
                    'value_name': '0.6 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '0.68 pF',
                    'value_name': '0.68 pF'},
                   {'product_count': 41,
                    'range_filter_type': None,
                    'value_id': '0.7 pF',
                    'value_name': '0.7 pF'},
                   {'product_count': 17,
                    'range_filter_type': None,
                    'value_id': '0.75 pF',
                    'value_name': '0.75 pF'},
                   {'product_count': 49,
                    'range_filter_type': None,
                    'value_id': '0.8 pF',
                    'value_name': '0.8 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '0.82 pF',
                    'value_name': '0.82 pF'},
                   {'product_count': 30,
                    'range_filter_type': None,
                    'value_id': '0.9 pF',
                    'value_name': '0.9 pF'},
                   {'product_count': 148,
                    'range_filter_type': None,
                    'value_id': '1 pF',
                    'value_name': '1 pF'},
                   {'product_count': 30,
                    'range_filter_type': None,
                    'value_id': '1.1 pF',
                    'value_name': '1.1 pF'},
                   {'product_count': 92,
                    'range_filter_type': None,
                    'value_id': '1.2 pF',
                    'value_name': '1.2 pF'},
                   {'product_count': 39,
                    'range_filter_type': None,
                    'value_id': '1.3 pF',
                    'value_name': '1.3 pF'},
                   {'product_count': 14,
                    'range_filter_type': None,
                    'value_id': '1.4 pF',
                    'value_name': '1.4 pF'},
                   {'product_count': 103,
                    'range_filter_type': None,
                    'value_id': '1.5 pF',
                    'value_name': '1.5 pF'},
                   {'product_count': 26,
                    'range_filter_type': None,
                    'value_id': '1.6 pF',
                    'value_name': '1.6 pF'},
                   {'product_count': 10,
                    'range_filter_type': None,
                    'value_id': '1.7 pF',
                    'value_name': '1.7 pF'},
                   {'product_count': 87,
                    'range_filter_type': None,
                    'value_id': '1.8 pF',
                    'value_name': '1.8 pF'},
                   {'product_count': 12,
                    'range_filter_type': None,
                    'value_id': '1.9 pF',
                    'value_name': '1.9 pF'},
                   {'product_count': 92,
                    'range_filter_type': None,
                    'value_id': '2 pF',
                    'value_name': '2 pF'},
                   {'product_count': 9,
                    'range_filter_type': None,
                    'value_id': '2.1 pF',
                    'value_name': '2.1 pF'},
                   {'product_count': 106,
                    'range_filter_type': None,
                    'value_id': '2.2 pF',
                    'value_name': '2.2 pF'},
                   {'product_count': 9,
                    'range_filter_type': None,
                    'value_id': '2.3 pF',
                    'value_name': '2.3 pF'},
                   {'product_count': 54,
                    'range_filter_type': None,
                    'value_id': '2.4 pF',
                    'value_name': '2.4 pF'},
                   {'product_count': 16,
                    'range_filter_type': None,
                    'value_id': '2.5 pF',
                    'value_name': '2.5 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '2.6 pF',
                    'value_name': '2.6 pF'},
                   {'product_count': 97,
                    'range_filter_type': None,
                    'value_id': '2.7 pF',
                    'value_name': '2.7 pF'},
                   {'product_count': 10,
                    'range_filter_type': None,
                    'value_id': '2.8 pF',
                    'value_name': '2.8 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '2.9 pF',
                    'value_name': '2.9 pF'},
                   {'product_count': 105,
                    'range_filter_type': None,
                    'value_id': '3 pF',
                    'value_name': '3 pF'},
                   {'product_count': 7,
                    'range_filter_type': None,
                    'value_id': '3.1 pF',
                    'value_name': '3.1 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '3.2 pF',
                    'value_name': '3.2 pF'},
                   {'product_count': 120,
                    'range_filter_type': None,
                    'value_id': '3.3 pF',
                    'value_name': '3.3 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '3.4 pF',
                    'value_name': '3.4 pF'},
                   {'product_count': 9,
                    'range_filter_type': None,
                    'value_id': '3.5 pF',
                    'value_name': '3.5 pF'},
                   {'product_count': 42,
                    'range_filter_type': None,
                    'value_id': '3.6 pF',
                    'value_name': '3.6 pF'},
                   {'product_count': 7,
                    'range_filter_type': None,
                    'value_id': '3.7 pF',
                    'value_name': '3.7 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '3.8 pF',
                    'value_name': '3.8 pF'},
                   {'product_count': 86,
                    'range_filter_type': None,
                    'value_id': '3.9 pF',
                    'value_name': '3.9 pF'},
                   {'product_count': 43,
                    'range_filter_type': None,
                    'value_id': '4 pF',
                    'value_name': '4 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '4.1 pF',
                    'value_name': '4.1 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '4.2 pF',
                    'value_name': '4.2 pF'},
                   {'product_count': 41,
                    'range_filter_type': None,
                    'value_id': '4.3 pF',
                    'value_name': '4.3 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '4.4 pF',
                    'value_name': '4.4 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '4.5 pF',
                    'value_name': '4.5 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '4.6 pF',
                    'value_name': '4.6 pF'},
                   {'product_count': 136,
                    'range_filter_type': None,
                    'value_id': '4.7 pF',
                    'value_name': '4.7 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '4.8 pF',
                    'value_name': '4.8 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '4.9 pF',
                    'value_name': '4.9 pF'},
                   {'product_count': 56,
                    'range_filter_type': None,
                    'value_id': '5 pF',
                    'value_name': '5 pF'},
                   {'product_count': 45,
                    'range_filter_type': None,
                    'value_id': '5.1 pF',
                    'value_name': '5.1 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '5.2 pF',
                    'value_name': '5.2 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '5.3 pF',
                    'value_name': '5.3 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '5.4 pF',
                    'value_name': '5.4 pF'},
                   {'product_count': 7,
                    'range_filter_type': None,
                    'value_id': '5.5 pF',
                    'value_name': '5.5 pF'},
                   {'product_count': 123,
                    'range_filter_type': None,
                    'value_id': '5.6 pF',
                    'value_name': '5.6 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '5.7 pF',
                    'value_name': '5.7 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '5.8 pF',
                    'value_name': '5.8 pF'},
                   {'product_count': 7,
                    'range_filter_type': None,
                    'value_id': '5.9 pF',
                    'value_name': '5.9 pF'},
                   {'product_count': 63,
                    'range_filter_type': None,
                    'value_id': '6 pF',
                    'value_name': '6 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '6.1 pF',
                    'value_name': '6.1 pF'},
                   {'product_count': 42,
                    'range_filter_type': None,
                    'value_id': '6.2 pF',
                    'value_name': '6.2 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '6.3 pF',
                    'value_name': '6.3 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '6.4 pF',
                    'value_name': '6.4 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '6.5 pF',
                    'value_name': '6.5 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '6.6 pF',
                    'value_name': '6.6 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '6.7 pF',
                    'value_name': '6.7 pF'},
                   {'product_count': 132,
                    'range_filter_type': None,
                    'value_id': '6.8 pF',
                    'value_name': '6.8 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '6.9 pF',
                    'value_name': '6.9 pF'},
                   {'product_count': 49,
                    'range_filter_type': None,
                    'value_id': '7 pF',
                    'value_name': '7 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '7.1 pF',
                    'value_name': '7.1 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '7.2 pF',
                    'value_name': '7.2 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '7.3 pF',
                    'value_name': '7.3 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '7.4 pF',
                    'value_name': '7.4 pF'},
                   {'product_count': 36,
                    'range_filter_type': None,
                    'value_id': '7.5 pF',
                    'value_name': '7.5 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '7.6 pF',
                    'value_name': '7.6 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '7.7 pF',
                    'value_name': '7.7 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '7.8 pF',
                    'value_name': '7.8 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '7.9 pF',
                    'value_name': '7.9 pF'},
                   {'product_count': 67,
                    'range_filter_type': None,
                    'value_id': '8 pF',
                    'value_name': '8 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '8.1 pF',
                    'value_name': '8.1 pF'},
                   {'product_count': 113,
                    'range_filter_type': None,
                    'value_id': '8.2 pF',
                    'value_name': '8.2 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '8.3 pF',
                    'value_name': '8.3 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '8.4 pF',
                    'value_name': '8.4 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '8.5 pF',
                    'value_name': '8.5 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '8.6 pF',
                    'value_name': '8.6 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '8.7 pF',
                    'value_name': '8.7 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '8.8 pF',
                    'value_name': '8.8 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '8.9 pF',
                    'value_name': '8.9 pF'},
                   {'product_count': 46,
                    'range_filter_type': None,
                    'value_id': '9 pF',
                    'value_name': '9 pF'},
                   {'product_count': 37,
                    'range_filter_type': None,
                    'value_id': '9.1 pF',
                    'value_name': '9.1 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '9.2 pF',
                    'value_name': '9.2 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '9.3 pF',
                    'value_name': '9.3 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '9.4 pF',
                    'value_name': '9.4 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '9.5 pF',
                    'value_name': '9.5 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '9.6 pF',
                    'value_name': '9.6 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '9.7 pF',
                    'value_name': '9.7 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '9.8 pF',
                    'value_name': '9.8 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '9.9 pF',
                    'value_name': '9.9 pF'},
                   {'product_count': 325,
                    'range_filter_type': None,
                    'value_id': '10 pF',
                    'value_name': '10 pF'},
                   {'product_count': 23,
                    'range_filter_type': None,
                    'value_id': '11 pF',
                    'value_name': '11 pF'},
                   {'product_count': 181,
                    'range_filter_type': None,
                    'value_id': '12 pF',
                    'value_name': '12 pF'},
                   {'product_count': 33,
                    'range_filter_type': None,
                    'value_id': '13 pF',
                    'value_name': '13 pF'},
                   {'product_count': 191,
                    'range_filter_type': None,
                    'value_id': '15 pF',
                    'value_name': '15 pF'},
                   {'product_count': 37,
                    'range_filter_type': None,
                    'value_id': '16 pF',
                    'value_name': '16 pF'},
                   {'product_count': 186,
                    'range_filter_type': None,
                    'value_id': '18 pF',
                    'value_name': '18 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '19 pF',
                    'value_name': '19 pF'},
                   {'product_count': 94,
                    'range_filter_type': None,
                    'value_id': '20 pF',
                    'value_name': '20 pF'},
                   {'product_count': 259,
                    'range_filter_type': None,
                    'value_id': '22 pF',
                    'value_name': '22 pF'},
                   {'product_count': 48,
                    'range_filter_type': None,
                    'value_id': '24 pF',
                    'value_name': '24 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '25 pF',
                    'value_name': '25 pF'},
                   {'product_count': 161,
                    'range_filter_type': None,
                    'value_id': '27 pF',
                    'value_name': '27 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '28 pF',
                    'value_name': '28 pF'},
                   {'product_count': 60,
                    'range_filter_type': None,
                    'value_id': '30 pF',
                    'value_name': '30 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '32 pF',
                    'value_name': '32 pF'},
                   {'product_count': 212,
                    'range_filter_type': None,
                    'value_id': '33 pF',
                    'value_name': '33 pF'},
                   {'product_count': 40,
                    'range_filter_type': None,
                    'value_id': '36 pF',
                    'value_name': '36 pF'},
                   {'product_count': 116,
                    'range_filter_type': None,
                    'value_id': '39 pF',
                    'value_name': '39 pF'},
                   {'product_count': 35,
                    'range_filter_type': None,
                    'value_id': '43 pF',
                    'value_name': '43 pF'},
                   {'product_count': 248,
                    'range_filter_type': None,
                    'value_id': '47 pF',
                    'value_name': '47 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '50 pF',
                    'value_name': '50 pF'},
                   {'product_count': 37,
                    'range_filter_type': None,
                    'value_id': '51 pF',
                    'value_name': '51 pF'},
                   {'product_count': 111,
                    'range_filter_type': None,
                    'value_id': '56 pF',
                    'value_name': '56 pF'},
                   {'product_count': 27,
                    'range_filter_type': None,
                    'value_id': '62 pF',
                    'value_name': '62 pF'},
                   {'product_count': 134,
                    'range_filter_type': None,
                    'value_id': '68 pF',
                    'value_name': '68 pF'},
                   {'product_count': 32,
                    'range_filter_type': None,
                    'value_id': '75 pF',
                    'value_name': '75 pF'},
                   {'product_count': 103,
                    'range_filter_type': None,
                    'value_id': '82 pF',
                    'value_name': '82 pF'},
                   {'product_count': 33,
                    'range_filter_type': None,
                    'value_id': '91 pF',
                    'value_name': '91 pF'},
                   {'product_count': 474,
                    'range_filter_type': None,
                    'value_id': '100 pF',
                    'value_name': '100 pF'},
                   {'product_count': 14,
                    'range_filter_type': None,
                    'value_id': '110 pF',
                    'value_name': '110 pF'},
                   {'product_count': 91,
                    'range_filter_type': None,
                    'value_id': '120 pF',
                    'value_name': '120 pF'},
                   {'product_count': 14,
                    'range_filter_type': None,
                    'value_id': '130 pF',
                    'value_name': '130 pF'},
                   {'product_count': 156,
                    'range_filter_type': None,
                    'value_id': '150 pF',
                    'value_name': '150 pF'},
                   {'product_count': 9,
                    'range_filter_type': None,
                    'value_id': '160 pF',
                    'value_name': '160 pF'},
                   {'product_count': 90,
                    'range_filter_type': None,
                    'value_id': '180 pF',
                    'value_name': '180 pF'},
                   {'product_count': 33,
                    'range_filter_type': None,
                    'value_id': '200 pF',
                    'value_name': '200 pF'},
                   {'product_count': 282,
                    'range_filter_type': None,
                    'value_id': '220 pF',
                    'value_name': '220 pF'},
                   {'product_count': 16,
                    'range_filter_type': None,
                    'value_id': '240 pF',
                    'value_name': '240 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '241 pF',
                    'value_name': '241 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '250 pF',
                    'value_name': '250 pF'},
                   {'product_count': 100,
                    'range_filter_type': None,
                    'value_id': '270 pF',
                    'value_name': '270 pF'},
                   {'product_count': 18,
                    'range_filter_type': None,
                    'value_id': '300 pF',
                    'value_name': '300 pF'},
                   {'product_count': 211,
                    'range_filter_type': None,
                    'value_id': '330 pF',
                    'value_name': '330 pF'},
                   {'product_count': 14,
                    'range_filter_type': None,
                    'value_id': '360 pF',
                    'value_name': '360 pF'},
                   {'product_count': 93,
                    'range_filter_type': None,
                    'value_id': '390 pF',
                    'value_name': '390 pF'},
                   {'product_count': 10,
                    'range_filter_type': None,
                    'value_id': '430 pF',
                    'value_name': '430 pF'},
                   {'product_count': 307,
                    'range_filter_type': None,
                    'value_id': '470 pF',
                    'value_name': '470 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '500 pF',
                    'value_name': '500 pF'},
                   {'product_count': 14,
                    'range_filter_type': None,
                    'value_id': '510 pF',
                    'value_name': '510 pF'},
                   {'product_count': 106,
                    'range_filter_type': None,
                    'value_id': '560 pF',
                    'value_name': '560 pF'},
                   {'product_count': 14,
                    'range_filter_type': None,
                    'value_id': '620 pF',
                    'value_name': '620 pF'},
                   {'product_count': 162,
                    'range_filter_type': None,
                    'value_id': '680 pF',
                    'value_name': '680 pF'},
                   {'product_count': 16,
                    'range_filter_type': None,
                    'value_id': '750 pF',
                    'value_name': '750 pF'},
                   {'product_count': 79,
                    'range_filter_type': None,
                    'value_id': '820 pF',
                    'value_name': '820 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '850 pF',
                    'value_name': '850 pF'},
                   {'product_count': 12,
                    'range_filter_type': None,
                    'value_id': '910 pF',
                    'value_name': '910 pF'},
                   {'product_count': 595,
                    'range_filter_type': None,
                    'value_id': '1000 pF',
                    'value_name': '1000 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '1100 pF',
                    'value_name': '1100 pF'},
                   {'product_count': 104,
                    'range_filter_type': None,
                    'value_id': '1200 pF',
                    'value_name': '1200 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '1300 pF',
                    'value_name': '1300 pF'},
                   {'product_count': 200,
                    'range_filter_type': None,
                    'value_id': '1500 pF',
                    'value_name': '1500 pF'},
                   {'product_count': 5,
                    'range_filter_type': None,
                    'value_id': '1600 pF',
                    'value_name': '1600 pF'},
                   {'product_count': 76,
                    'range_filter_type': None,
                    'value_id': '1800 pF',
                    'value_name': '1800 pF'},
                   {'product_count': 15,
                    'range_filter_type': None,
                    'value_id': '2000 pF',
                    'value_name': '2000 pF'},
                   {'product_count': 319,
                    'range_filter_type': None,
                    'value_id': '2200 pF',
                    'value_name': '2200 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '2400 pF',
                    'value_name': '2400 pF'},
                   {'product_count': 98,
                    'range_filter_type': None,
                    'value_id': '2700 pF',
                    'value_name': '2700 pF'},
                   {'product_count': 8,
                    'range_filter_type': None,
                    'value_id': '3000 pF',
                    'value_name': '3000 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '3200 pF',
                    'value_name': '3200 pF'},
                   {'product_count': 210,
                    'range_filter_type': None,
                    'value_id': '3300 pF',
                    'value_name': '3300 pF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '3600 pF',
                    'value_name': '3600 pF'},
                   {'product_count': 71,
                    'range_filter_type': None,
                    'value_id': '3900 pF',
                    'value_name': '3900 pF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '4300 pF',
                    'value_name': '4300 pF'},
                   {'product_count': 295,
                    'range_filter_type': None,
                    'value_id': '4700 pF',
                    'value_name': '4700 pF'},
                   {'product_count': 11,
                    'range_filter_type': None,
                    'value_id': '5100 pF',
                    'value_name': '5100 pF'},
                   {'product_count': 67,
                    'range_filter_type': None,
                    'value_id': '5600 pF',
                    'value_name': '5600 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '6200 pF',
                    'value_name': '6200 pF'},
                   {'product_count': 147,
                    'range_filter_type': None,
                    'value_id': '6800 pF',
                    'value_name': '6800 pF'},
                   {'product_count': 6,
                    'range_filter_type': None,
                    'value_id': '7500 pF',
                    'value_name': '7500 pF'},
                   {'product_count': 52,
                    'range_filter_type': None,
                    'value_id': '8200 pF',
                    'value_name': '8200 pF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '9100 pF',
                    'value_name': '9100 pF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '9200 pF',
                    'value_name': '9200 pF'},
                   {'product_count': 9,
                    'range_filter_type': None,
                    'value_id': '0.01 µF',
                    'value_name': '0.01 µF'},
                   {'product_count': 546,
                    'range_filter_type': None,
                    'value_id': '10000 pF',
                    'value_name': '10000 pF'},
                   {'product_count': 36,
                    'range_filter_type': None,
                    'value_id': '0.012 µF',
                    'value_name': '0.012 µF'},
                   {'product_count': 119,
                    'range_filter_type': None,
                    'value_id': '0.015 µF',
                    'value_name': '0.015 µF'},
                   {'product_count': 1,
                    'range_filter_type': None,
                    'value_id': '0.016 µF',
                    'value_name': '0.016 µF'},
                   {'product_count': 34,
                    'range_filter_type': None,
                    'value_id': '0.018 µF',
                    'value_name': '0.018 µF'},
                   {'product_count': 2,
                    'range_filter_type': None,
                    'value_id': '0.02 µF',
                    'value_name': '0.02 µF'},
                   {'product_count': 237,
                    'range_filter_type': None,
                    'value_id': '0.022 µF',
                    'value_name': '0.022 µF'},
                   {'product_count': 49,
                    'range_filter_type': None,
                    'value_id': '0.027 µF',
                    'value_name': '0.027 µF'},
                   {'product_count': 133,
                    'range_filter_type': None,
                    'value_id': '0.033 µF',
                    'value_name': '0.033 µF'},
                   {'product_count': 37,
                    'range_filter_type': None,
                    'value_id': '0.039 µF',
                    'value_name': '0.039 µF'},
                   {'product_count': 243,
                    'range_filter_type': None,
                    'value_id': '0.047 µF',
                    'value_name': '0.047 µF'},
                   {'product_count': 36,
                    'range_filter_type': None,
                    'value_id': '0.056 µF',
                    'value_name': '0.056 µF'},
                   {'product_count': 112,
                    'range_filter_type': None,
                    'value_id': '0.068 µF',
                    'value_name': '0.068 µF'},
                   {'product_count': 35,
                    'range_filter_type': None,
                    'value_id': '0.082 µF',
                    'value_name': '0.082 µF'},
                   {'product_count': 683,
                    'range_filter_type': None,
                    'value_id': '0.1 µF',
                    'value_name': '0.1 µF'},
                   {'product_count': 32,
                    'range_filter_type': None,
                    'value_id': '0.12 µF',
                    'value_name': '0.12 µF'},
                   {'product_count': 89,
                    'range_filter_type': None,
                    'value_id': '0.15 µF',
                    'value_name': '0.15 µF'},
                   {'product_count': 16,
                    'range_filter_type': None,
                    'value_id': '0.18 µF',
                    'value_name': '0.18 µF'},
                   {'product_count': 326,
                    'range_filter_type': None,
                    'value_id': '0.22 µF',
                    'value_name': '0.22 µF'},
                   {'product_count': 13,
                    'range_filter_type': None,
                    'value_id': '0.27 µF',
                    'value_name': '0.27 µF'},
                   {'product_count': 116,
                    'range_filter_type': None,
                    'value_id': '0.33 µF',
                    'value_name': '0.33 µF'},
                   {'product_count': 12,
                    'range_filter_type': None,
                    'value_id': '0.39 µF',
                    'value_name': '0.39 µF'},
                   {'product_count': 266,
                    'range_filter_type': None,
                    'value_id': '0.47 µF',
                    'value_name': '0.47 µF'},
                   {'product_count': 4,
                    'range_filter_type': None,
                    'value_id': '0.56 µF',
                    'value_name': '0.56 µF'},
                   {'product_count': 66,
                    'range_filter_type': None,
                    'value_id': '0.68 µF',
                    'value_name': '0.68 µF'},
                   {'product_count': 9,
                    'range_filter_type': None,
                    'value_id': '0.82 µF',
                    'value_name': '0.82 µF'},
                   {'product_count': 408,
                    'range_filter_type': None,
                    'value_id': '1 µF',
                    'value_name': '1 µF'},
                   {'product_count': 13,
                    'range_filter_type': None,
                    'value_id': '1.5 µF',
                    'value_name': '1.5 µF'},
                   {'product_count': 218,
                    'range_filter_type': None,
                    'value_id': '2.2 µF',
                    'value_name': '2.2 µF'},
                   {'product_count': 13,
                    'range_filter_type': None,
                    'value_id': '3.3 µF',
                    'value_name': '3.3 µF'},
                   {'product_count': 170,
                    'range_filter_type': None,
                    'value_id': '4.7 µF',
                    'value_name': '4.7 µF'},
                   {'product_count': 169,
                    'range_filter_type': None,
                    'value_id': '10 µF',
                    'value_name': '10 µF'},
                   {'product_count': 3,
                    'range_filter_type': None,
                    'value_id': '15 µF',
                    'value_name': '15 µF'},
                   {'product_count': 72,
                    'range_filter_type': None,
                    'value_id': '22 µF',
                    'value_name': '22 µF'},
                   {'product_count': 29,
                    'range_filter_type': None,
                    'value_id': '47 µF',
                    'value_name': '47 µF'}],
 'parameter_id': 2049,
 'parameter_name': 'Capacitance',
 'parameter_type': 'UnitOfMeasure'}