{'filter_options_request': {'category_filter': [{'Id': 52}],
                            'manufacturer_filter': None,
                            'market_place_filter': None,
                            'minimum_quantity_available': 1,
                            'packaging_filter': None,
                            'parameter_filter_request': {'category_filter': {'Id': 52},
                                                         'parameter_filters': [{'filter_values': [{'Id': '9.53 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '9.65 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '9.76 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '9.79 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '9.88 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '10 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '10.1 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '10.2 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '10.4 '
                                                                                                         'kOhms'},
                                                                                                  {'Id': '10.5 '
                                                                                                         'kOhms'}],
                                                                                'parameter_id': 2085},
                                                                               {'filter_values': [{'Id': '651'},
                                                                                                  {'Id': '667'},
                                                                                                  {'Id': '696'},
                                                                                                  {'Id': '731'},
                                                                                                  {'Id': '848'}],
                                                                                'parameter_id': 3},
                                                                               {'filter_values': [{'Id': '14064'},
                                                                                                  {'Id': '11096'},
                                                                                                  {'Id': '10879'},
                                                                                                  {'Id': '12371'},
                                                                                                  {'Id': '12631'},
                                                                                                  {'Id': '18038'},
                                                                                                  {'Id': '759691'},
                                                                                                  {'Id': '16543'},
                                                                                                  {'Id': '21930'},
                                                                                                  {'Id': '19246'},
                                                                                                  {'Id': '19368'},
                                                                                                  {'Id': '20896'},
                                                                                                  {'Id': '25160'},
                                                                                                  {'Id': '25166'},
                                                                                                  {'Id': '28682'},
                                                                                                  {'Id': '33182'},
                                                                                                  {'Id': '121219'},
                                                                                                  {'Id': '55874'},
                                                                                                  {'Id': '169141'},
                                                                                                  {'Id': '130344'},
                                                                                                  {'Id': '203013'},
                                                                                                  {'Id': '249624'}],
                                                                                'parameter_id': 2},
                                                                               {'filter_values': [{'Id': '262184'},
                                                                                                  {'Id': '262188'},
                                                                                                  {'Id': '242934'},
                                                                                                  {'Id': '242940'},
                                                                                                  {'Id': '242941'},
                                                                                                  {'Id': '242948'},
                                                                                                  {'Id': '242956'},
                                                                                                  {'Id': '242957'},
                                                                                                  {'Id': '242960'},
                                                                                                  {'Id': '242963'},
                                                                                                  {'Id': '795880'},
                                                                                                  {'Id': '242965'}],
                                                                                'parameter_id': 252},
                                                                               {'filter_values': [{'Id': '39246'}],
                                                                                'parameter_id': 16},
                                                                               {'filter_values': [{'Id': '39245'}],
                                                                                'parameter_id': 1291}]},
                            'search_options': None,
                            'series_filter': None,
                            'status_filter': [{'Id': 0}]},
 'keywords': 'resistor 0603',
 'limit': 10,
 'offset': None}