{'filter_options_request': {'category_filter': None,
                            'manufacturer_filter': None,
                            'market_place_filter': None,
                            'minimum_quantity_available': None,
                            'packaging_filter': None,
                            'parameter_filter_request': None,
                            'search_options': None,
                            'series_filter': None,
                            'status_filter': [{'Id': 0}]},
 'keywords': 'resistor',
 'limit': 1,
 'offset': None}