{'filter_options_request': {'category_filter': [{'Id': 52}],
                            'manufacturer_filter': None,
                            'market_place_filter': None,
                            'minimum_quantity_available': 1,
                            'packaging_filter': None,
                            'parameter_filter_request': {'category_filter': {'Id': 52},
                                                         'parameter_filters': [{'filter_values': [{'Id': '10 '
                                                                                                         'kOhms'}],
                                                                                'parameter_id': 2085},
                                                                               {'filter_values': [{'Id': '848'}],
                                                                                'parameter_id': 3},
                                                                               {'filter_values': [{'Id': '14064'}],
                                                                                'parameter_id': 2},
                                                                               {'filter_values': [{'Id': '285941'},
                                                                                                  {'Id': '262184'},
                                                                                                  {'Id': '262188'},
                                                                                                  {'Id': '262189'},
                                                                                                  {'Id': '262192'},
                                                                                                  {'Id': '262196'},
                                                                                                  {'Id': '262203'},
                                                                                                  {'Id': '242934'},
                                                                                                  {'Id': '242940'},
                                                                                                  {'Id': '242941'},
                                                                                                  {'Id': '242944'},
                                                                                                  {'Id': '242948'},
                                                                                                  {'Id': '242956'},
                                                                                                  {'Id': '242957'},
                                                                                                  {'Id': '242960'},
                                                                                                  {'Id': '242963'},
                                                                                                  {'Id': '795880'},
                                                                                                  {'Id': '242965'},
                                                                                                  {'Id': '242968'},
                                                                                                  {'Id': '242969'}],
                                                                                'parameter_id': 252},
                                                                               {'filter_values': [{'Id': '39246'}],
                                                                                'parameter_id': 16}]},
                            'search_options': None,
                            'series_filter': None,
                            'status_filter': [{'Id': 0}]},
 'keywords': 'resistor',
 'limit': 10,
 'offset': None}